# Generated by Django 2.2 on 2020-11-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_auto_20201121_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='klin_url',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
