# Generated by Django 2.2 on 2020-12-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='created_by',
        ),
    ]
