# Generated by Django 2.2 on 2020-12-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_remove_url_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to='url_shortener.Author'),
        ),
    ]
