# Generated by Django 2.2 on 2020-12-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0004_url_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='klin_url',
            field=models.CharField(default='null', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='long_url',
            field=models.URLField(default='null', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
