# Generated by Django 2.2 on 2020-12-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0005_auto_20201210_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
