# Generated by Django 2.2 on 2020-12-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0006_url_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='slug',
            field=models.SlugField(default='null', max_length=6),
            preserve_default=False,
        ),
    ]
